strategy:
  name: Straddle
  slippage: 1.0
  symbol: banknifty
  # 0=Sunday 1=Monday 2=Tuesday 3=Wednesday 4=Thursday 5=Friday 6=Saturday
  days_to_run: 3,4
  stop:
    - type: stop_type_time
      time: 15:20
    - type: stop_type_mtm_amount
      amount: -10000
  legs:
    - lots: 3
      buy_or_sell: sell
      ce_or_pe: CE
      strike_selection:
        type: strike_selection_type_distance_from_spot
        distance_from_spot: 0
        #type: strike_selection_type_near_ltp
        #near_ltp: 15
        #type: strike_selection_type_range_ltp
        #min_ltp: 10
        #max_ltp: 25
      entry:
        - type: entry_type_time
          time: "09:18"
      exit:
        - type: exit_type_time
          time: "15:25"
        - type: exit_type_ltp_loss_percent
          percent: 50.0

    - lots: 3
      buy_or_sell: sell
      ce_or_pe: PE
      strike_selection:
        type: strike_selection_type_distance_from_spot
        distance_from_spot: 0
        #type: strike_selection_type_near_ltp
        #near_ltp: 15
        #type: strike_selection_type_range_ltp
        #min_ltp: 10
        #max_ltp: 25
      entry:
        - type: entry_type_time
          time: "09:18"
      exit:
        - type: exit_type_time
          time: "15:25"
        - type: exit_type_ltp_loss_percent
          percent: 50.0
